#!/bin/bash

rm -rf .flatpak-builder/ build-dir/ builder.yml > /dev/null 2>&1

echo -e "[\e[0;92mBUILDER_SCRIPT\e[0m] Templating the original file, hold still."

DEBSHA=$(curl -sL https://deb.debian.org/debian/indices/files/arch-amd64.files | sha256sum)
DEBSHA=$(echo "${DEBSHA}" | cut -d " " -f1)
m4 -D Xdebsha="${DEBSHA}" com.etternaonline.Etterna.yml > builder.yml

echo -e "[\e[0;92mBUILDER_SCRIPT\e[0m] Building the Flatpak. This script shouldn't error out.\nIf anything goes wrong, report it to the devs."

flatpak-builder --user --install --force-clean build-dir builder.yml > /dev/null 2>&1 &

while [ ! -d ".flatpak-builder/build/etterna/Etterna" ]; do sleep 5; done
while [ ! -f ".flatpak-builder/build/etterna/debian.proper.files" ]; do sleep 5; done

echo -e "[\e[0;92mBUILDER_SCRIPT\e[0m] Hacking into the Matrix.."

wget -i .flatpak-builder/build/etterna/debian.proper.files
mv libglu* .flatpak-builder/build/etterna
touch .flatpak-builder/build/etterna/DONE

while [ -d ".flatpak-builder/build/etterna" ]; do sleep 5; done

echo -e "[\e[1;92mBUILDER_SCRIPT\e[0m] Flatpak built and installed."
